### ISSUE TITLE
No utopic PPA?

### ISSUE THREAD

**Issue by oylenshpeegul** [minos-org/ffcast#3]
When I followed the ubuntu directions on this 14.10 machine, it failed

```
$ sudo apt-get update
...
W: Failed to fetch http://ppa.launchpad.net/minos-archive/main/ubuntu/dists/utopic/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/minos-archive/main/ubuntu/dists/utopic/main/binary-i386/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

No utopic?

**Comment by javier-lopez** [comment]
Hi,

Only Ubuntu LTS versions are supported. You could edit the **/etc/apt/source-list.d/minos**\* file and change "utopic" with "trusty" to install the package, though. Compiling from source is also an option.
