### ISSUE TITLE
Example to record Window from PC audio, not microphone ?

### ISSUE THREAD

**Issue by stuaxo** [minos-org/ffcast#4]
Any idea how to record a window monitoring the PC audio instead of recording from the microphone ?

**Comment by chilicuil** [comment]
Hi,

This is how I do it in my setup (just alsa installed) it may or may not work in your own environment.

- 1) Create a file called **~/.asoundrc** with the following:

```
pcm.multi {
    type route;
    slave.pcm {
        type multi;
        slaves.a.pcm "output";
        slaves.b.pcm "loopin";
        slaves.a.channels 2;
        slaves.b.channels 2;
        bindings.0.slave a;
        bindings.0.channel 0;
        bindings.1.slave a;
        bindings.1.channel 1;
        bindings.2.slave b;
        bindings.2.channel 0;
        bindings.3.slave b;
        bindings.3.channel 1;
    }

    ttable.0.0 1;
    ttable.1.1 1;
    ttable.0.2 1;
    ttable.1.3 1;
}

pcm.!default {
    type plug
        slave.pcm "multi"
}

pcm.output {
    type hw
        card Intel
}

pcm.loopin {
    type plug
        slave.pcm "hw:Loopback,0,0"
}

pcm.loopout {
    type plug
        slave.pcm "hw:Loopback,1,0"
}
```

- 2) Replace **Intel** in the above entry with your own audio card  (see `aplay -L | grep CARD` for hints) and save the file

- 3A) Record (this may have audio/video sync problems)

```
ffcast -w ffmpeg -y -- -f alsa -i hw:Loopback,1,0 -vcodec libx264  output.mkv
```

- 3B) Record (fixing audio/video sync problems)

```
ffcast -w ffmpeg -y -- -f alsa -i hw:Loopback,1,0 -vcodec libx264 -preset ultrafast  output.mkv
```

- 4) Play some music in other terminal `mplayer audio.ogg`

- 5) Stop recording `ffcast -k`

https://trac.ffmpeg.org/wiki/Capture/ALSA
http://ubuntuforums.org/showthread.php?t=2170398
https://trac.ffmpeg.org/ticket/692

Good luck =)!
