### ISSUE TITLE
Does not offset?

### ISSUE THREAD

**Issue by fbm-static** [minos-org/ffcast#5]
Hello,

Thank you so much for the nice tool. However, I'm having a problem. When a select an area through my mouse, the recorded part is from the upperleft-corner of my screen ( instead of upper-left corner of my selection) to the lower-right corner of the selection.

My distro is ArchLinux.
My WM is xmonad.

**Comment by chilicuil** [comment]
Hi @fbm-static, 

I cannot reproduce the issue on i3-wm, the error seems to be in the coordinates `xrectsel` reports, try replacing your current xrectsel binary with this one:

https://github.com/lolilolicon/xrectsel

And see if that fixes your issue, if it doesn't please run xrectsel under gdb and attach a backtrace.

Regards
